C_STANDARD_FLAG = --std-$(C_STANDARD)
FREESTANDING_FLAG =
NOSTDLIB_FLAG = --nostdlib
BASE_WARNING_FLAGS =
WERROR_FLAG = --Werror
DEBUG_SYMBOLS_FLAG = --debug
GENERIC_OPTIMIZATION_FLAG =
OBJECT_EXT = rel
ifneq ($(TARGET_ARCHITECTURE),)
	ARCH_FLAG = -m$(TARGET_ARCHITECTURE)
endif
