# Because Make interprets # as a comment, even inside a multiline string, we use
# backticks here and replace them later.
define CONFIGURATION_HEADER_TEXT
/* AUTOGENERATED -- DO NOT MODIFY */
`ifndef MDL_CONFIGURATION_H_
`define MDL_CONFIGURATION_H_
`define MDL_VERSION_MAJOR $(VERSION_MAJOR)
`define MDL_VERSION_MINOR $(VERSION_MINOR)
`define MDL_VERSION_PATCH $(VERSION_PATCH)
`define MDL_VERSION_FULL ((MDL_VERSION_MAJOR * 10000) + \
                         (MDL_VERSION_MINOR * 100) + \
                         MDL_VERSION_PATCH)
`define MDL_VERSION_FULL_STRING "$(VERSION_FULL)"
`define MDL_COMPILED_AS_UNHOSTED $(UNHOSTED_IMPLEMENTATION)
`if !defined(MDL_CURRENTLY_COMPILING_LIBRARY) &&                               \
    !defined(MDL_CURRENTLY_COMPILING_TESTS) && defined(__STDC_HOSTED__)
`    if !MDL_COMPILED_AS_UNHOSTED && !__STDC_HOSTED__
`        error "Program is unhosted. Recompile MetalData for unhosted code."
`    endif
`endif /* __STDC_HOSTED__ */
`endif /* MDL_CONFIGURATION_H_ */
endef
