# Because Make interprets # as a comment, even inside a multiline string, we use
# backticks here and replace them later.
define CONFIGURATION_HEADER_TEXT
/* AUTOGENERATED -- DO NOT MODIFY */

// SPDX-License-Identifier: MPL-2.0+
// Copyright (C) 2020-2025  Diego Argueta
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

`ifndef MDL_CONFIGURATION_H_
`define MDL_CONFIGURATION_H_
`define MDL_VERSION_MAJOR $(VERSION_MAJOR)
`define MDL_VERSION_MINOR $(VERSION_MINOR)
`define MDL_VERSION_PATCH $(VERSION_PATCH)
`define MDL_MAKE_VERSION(x, y, z) (((x)*10000) + ((y)*100) + (z))
`define MDL_VERSION_FULL                                                       \
    MDL_MAKE_VERSION(MDL_VERSION_MAJOR, MDL_VERSION_MINOR, MDL_VERSION_PATCH)
`define MDL_VERSION_FULL_STRING "$(VERSION_FULL)"
`define MDL_COMPILED_AS_UNHOSTED $(UNHOSTED_IMPLEMENTATION)
`if !defined(MDL_CURRENTLY_COMPILING_LIBRARY) &&                               \
    !defined(MDL_CURRENTLY_COMPILING_TESTS) && defined(__STDC_HOSTED__)
`    if !MDL_COMPILED_AS_UNHOSTED && !__STDC_HOSTED__
`        error "Program is unhosted. Recompile MetalData for unhosted code."
`    endif
`endif /* __STDC_HOSTED__ */
`endif /* MDL_CONFIGURATION_H_ */
endef
