#ifndef INCLUDE_METALDATA_ERRORS_H_
#define INCLUDE_METALDATA_ERRORS_H_

#include "configuration.h"

#define MDL_EOF (-1)
#define MDL_OK 0
#define MDL_ERROR_EMPTY 1
#define MDL_ERROR_MODIFIED_ITERABLE 2
#define MDL_ERROR_NOT_FOUND 3
#define MDL_ERROR_ALREADY_EXISTS 4
#define MDL_ERROR_ASSERT_FAILED 5
#define MDL_ERROR_FULL 6
#define MDL_ERROR_NOMEM 7
#define MDL_ERROR_OUT_OF_RANGE 8

#endif /* INCLUDE_METALDATA_ERRORS_H_ */
