name: CI

on: [ push ]

jobs:
  testing:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
          - macos-latest
        compiler:
          - binary: clang
            configure-flags: ""
          - binary: gcc
            configure-flags: ""
          - binary: tcc
            configure-flags: ""
        unhosted-flag:
          - ""
          - "-u"
        exclude:
          # TODO (dargueta): Figure out what to do about incompatible headers
          - operating-system: macos-latest
            compiler:
              binary: tcc
    steps:
      - uses: actions/checkout@v3

      - name: Install Compilers
        uses: ConorMacBride/install-package@v1
        with:
          apt: clang gcc-mingw-w64 tcc
          brew: gcc mingw-w64

      - name: Configure
        run: |
          ./configure -d \
                      --cc=${{ matrix.compiler.binary }} \
                      ${{ matrix.unhosted-flag }} \
                      ${{ matrix.compiler.configure-flags }}

      - name: Compile
        run: make library

      - name: Test Installation
        run: sudo make install

      - name: Run Tests
        run: make test

  testing-sdcc:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture:
          - ds390
          - ds400
          - ez80_z80
          - hc08
          - mcs51
          - mos6502
          - pdk13
          - pdk14
          - pdk15
          - r2k
          - r2ka
          - r3ka
          - s08
          - sm83
          - stm8
          - tlcs90
          - z180
          - z80
          - z80n
          # These require additional work with flags, uncomment later
          # - pic14
          # - pic16
          #
          # Uncomment once we upgrade to 4.3+
          # - mos65c02
          # - r800
          #
          # Something weird is going on with this one, possibly another SDCC bug.
          # - TININative
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        # 4.3.0+ are broken: https://sourceforge.net/p/sdcc/bugs/3715/
        run: make -C make -f compiler-support/install.mk install-sdcc SDCC_VERSION=4.2.0
      - name: Configure
        run: ./configure --cc=sdcc -m ${{ matrix.architecture }}
      - name: Compile
        run: make library
