name: CI

on: [ push ]

jobs:
  testing:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
          - macos-latest
        compiler:
          - binary: clang
            configure-flags: ""
          - binary: gcc
            configure-flags: ""
          - binary: tcc
            configure-flags: t
          - binary: sdcc
            configure-flags: m
          - binary: pcc
            configure-flags: t
        unhosted-flag:
          - ""
          - "u"
        exclude:
          # SDCC has a bug in it on macOS that causes compilation to fail.
          - operating-system: macos-latest
            compiler:
              binary: sdcc
    steps:
      - uses: actions/checkout@v3

      - name: Fix PATH on MacOS for TCC
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Install Compilers
        uses: ConorMacBride/install-package@v1
        with:
          apt: mingw-w64 pcc sdcc tcc
          brew: sdcc

      # TCC can't be installed via Homebrew on recent versions of macOS because
      # of an "upstream incompatibility".
      - name: Install TCC on MacOS
        if: matrix.operating-system == 'macos-latest' && matrix.compiler.binary == 'tcc'
        run: make -C make -f compilers.mk install-pcc

      - name: Install PCC on MacOS
        if: matrix.operating-system == 'macos-latest' && matrix.compiler.binary == 'pcc'
        run: make -C make -f compilers.mk install-pcc

      - name: Configure
        run: ./configure -d${{ matrix.unhosted-flag }}${{ matrix.compiler.configure-flags }}

      - name: Compile
        run: make library CC=${{ matrix.compiler.binary }}

      - name: Test Installation
        run: sudo make install

      - name: Run Tests
        # We can't run cross-platform tests on SDCC
        if: matrix.compiler.binary != 'sdcc'
        run: make test CC=${{ matrix.compiler.binary }}

  testing-windows:
    runs-on: windows-latest
    env:
      SHELLOPTS: igncr
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe -o igncr '{0}'
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - binary: clang
            # Warnings need to be non-fatal when compiling tests due to an unused
            # static function in munit.
            configure-flags: t
          - binary: gcc
            configure-flags: ""
          - binary: tcc
            configure-flags: t
#          - binary: sdcc
#            configure-flags: m
        unhosted-flag:
          - ""
          - "u"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: clang gcc perl texinfo

      - name: Install TCC if needed
        if: matrix.compiler.binary == 'tcc'
        run: make -C make -f compilers.mk install-tcc

      - name: Fix PATH for TCC
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Configure
        run: ./configure -d${{ matrix.unhosted-flag }}${{ matrix.compiler.configure-flags }}

      - name: Compile
        run: make library CC=${{ matrix.compiler.binary }}

      - name: Test Installation
        # Cygwin doesn't have sudo
        run: make install

      - name: Run Tests
        # We can't run cross-platform tests on SDCC
        if: matrix.compiler.binary != 'sdcc'
        run: make test CC=${{ matrix.compiler.binary }}
