name: CI

on: [ push ]

jobs:
  testing:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
          - macos-latest
        compiler:
          - binary: clang
            configure-flags: ""
          - binary: gcc
            configure-flags: ""
          - binary: tcc
            configure-flags: w
          - binary: sdcc
            configure-flags: m
        unhosted-flag:
          - ""
          - "u"
        include:
          - operating-system: ubuntu-latest
            compiler:
              binary: pcc
              configure-flags: w
            unhosted-flag: ""
          - operating-system: ubuntu-latest
            compiler:
              binary: pcc
              configure-flags: w
            unhosted-flag: u
        exclude:
          # SDCC has a bug in it on macOS that causes compilation to fail.
          - operating-system: macos-latest
            compiler:
              binary: sdcc
    steps:
      - uses: actions/checkout@v3
      - name: Install Compilers
        uses: ConorMacBride/install-package@v1
        with:
          apt: pcc sdcc tcc
          brew: sdcc
      # TCC can't be installed via Homebrew on recent versions of macOS because
      # of an "upstream incompatibility".
      - name: Install TCC on MacOS
        if: matrix.operating-system == 'macos-latest' && matrix.compiler.binary == 'tcc'
        run: |
          curl http://download-mirror.savannah.gnu.org/releases/tinycc/tcc-0.9.27.tar.bz2 | tar -xj
          cd tcc-0.9.27
          ./configure 
          make 
          sudo make install
      - name: Configure
        run: ./configure -d${{ matrix.unhosted-flag }}${{ matrix.compiler.configure-flags }}
      - name: Compile
        run: make library CC=${{ matrix.compiler.binary }}
      - name: Run Tests
        # We can't run cross-platform tests on SDCC
        if: matrix.compiler.binary != 'sdcc'
        run: make test CC=${{ matrix.compiler.binary }}

  testing-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe -o igncr '{0}'
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - binary: clang
            configure-flags: ""
          - binary: gcc
            configure-flags: ""
          - binary: tcc
            configure-flags: w
#          - binary: sdcc
#            configure-flags: m
        unhosted-flag:
          - ""
          - "u"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: clang gcc-g++ perl texinfo
      - name: Install TCC if needed
        if: matrix.compiler.binary == 'tcc'
        run: |
          curl http://download-mirror.savannah.gnu.org/releases/tinycc/tcc-0.9.27.tar.bz2 | tar -xj
          cd tcc-0.9.27
          ./configure 
          make 
          sudo make install
      - name: Configure
        run: |
          pwd
          ls -lAh
          ./configure -d${{ matrix.unhosted-flag }}${{ matrix.compiler.configure-flags }}
      - name: Compile
        run: make library CC=${{ matrix.compiler.binary }}
      - name: Run Tests
        # We can't run cross-platform tests on SDCC
        if: matrix.compiler.binary != 'sdcc'
        run: make test CC=${{ matrix.compiler.binary }}
