name: CI

on: [ push ]

jobs:
  testing:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
          - macos-latest
        compiler:
          - binary: clang
            configure-flags: ""
          - binary: gcc
            configure-flags: ""
          - binary: tcc
            configure-flags: w
          - binary: sdcc
            configure-flags: m
        unhosted-flag:
          - ""
          - "u"
        # include:
        #   - operating-system: ubuntu-latest
        #     compiler:
        #       binary: pcc
        #       configure-flags: w
        exclude:
          # SDCC has a bug in it on macOS that causes compilation to fail.
          - operating-system: macos-latest
            compiler:
              binary: sdcc
    steps:
      - uses: actions/checkout@v3
      - name: Install Compilers
        uses: ConorMacBride/install-package@v1
        with:
          apt: pcc sdcc tcc
          brew: sdcc
          choco: tcc sdcc
      # TCC can't be installed via Homebrew on recent versions of macOS because
      # of an "upstream incompatibility".
      - name: Install TCC on MacOS
        if: matrix.operating-system == 'macos-latest' && matrix.compiler.binary == 'tcc'
        run: |
          curl https://download.savannah.gnu.org/releases/tinycc/tcc-0.9.27.tar.bz2 | tar -xv ;
          ls -lAh ;
          cd tcc-0.9.27 && sudo gmake install ;
      - name: Configure
        run: ./configure -d${{ matrix.unhosted-flag }}${{ matrix.compiler.configure-flags }}
      - name: Compile
        run: make library CC=${{ matrix.compiler.binary }}
      - name: Run Tests
        # We can't run cross-platform tests on SDCC
        if: matrix.compiler.binary != 'sdcc'
        run: make test CC=${{ matrix.compiler.binary }}
