name: CI

on: [ push ]

jobs:
  testing:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
          - macos-latest
        compiler:
          - binary: clang
          - binary: gcc
          - binary: tcc
        unhosted-flag:
          - ""
          - "-u"
        exclude:
          # TODO (dargueta): Figure out what to do about incompatible headers
          - operating-system: macos-latest
            compiler:
              binary: tcc
    steps:
      - uses: actions/checkout@v4

      - name: Install Compilers
        uses: ConorMacBride/install-package@v1
        with:
          apt: clang gcc-mingw-w64 tcc
          brew: gcc mingw-w64

      - name: Configure
        run: |
          ./configure -d \
                      --cc=${{ matrix.compiler.binary }} \
                      ${{ matrix.unhosted-flag }}
      - name: Compile
        run: make library
      - name: Install
        run: sudo make install
      - name: Run Tests
        run: make test

  testing-sdcc:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture:
          - ds390
          - ds400
          - ez80_z80
          - hc08
          - mcs51
          - mos6502
          - pdk13
          - pdk14
          - pdk15
          - r2k
          - r2ka
          - r3ka
          - s08
          - sm83
          - stm8
          - tlcs90
          - z180
          - z80
          - z80n
          # These require additional work with flags, uncomment later
          # - pic14
          # - pic16
          #
          # Uncomment once we upgrade to 4.3+
          # - mos65c02
          # - r800
          #
          # Something weird is going on with this one, possibly another SDCC bug.
          # - TININative
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        # 4.3.0+ are broken: https://sourceforge.net/p/sdcc/bugs/3715/
        run: make -C make -f compiler-support/install.mk install-sdcc SDCC_VERSION=4.2.0
      - name: Configure
        run: ./configure --cc=sdcc -m ${{ matrix.architecture }}
      - name: Compile
        run: make library

  testing-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - binary: clang
          - binary: gcc
          - binary: x86_64-w64-mingw32-gcc
        unhosted-flag:
          - ""
          - "-u"
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v4
      - uses: cygwin/cygwin-install-action@v4
        with:
          packages: >-
            clang
            gcc
            make
            mingw64-i686-gcc-core
            mingw64-x86_64-gcc-core
      - name: Configure
        run: ./configure --cc ${{ matrix.compiler.binary }} ${{ matrix.unhosted-flag }}
        shell: C:\cygwin\bin\bash.exe '{0}'
      - name: Compile
        run: make library
      - name: Install
        run: make install
      - name: Run Tests
        run: make test
#
#  testing-watcom:
#    runs-on: windows-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        architecture:
#          - i86
#          - i186
#          - i286
#          - i386
#    steps:
#      - run: git config --global core.autocrlf input
#      - uses: actions/checkout@v4
#      - uses: cygwin/cygwin-install-action@v4
#        with:
#          packages: >-
#            coreutils
#            make
#      - name: Install Watcom
#        uses: open-watcom/setup-watcom@v0
#        with:
#          version: "2.0"
#      - name: Configure
#        run: ./configure --cc=owcc -m ${{ matrix.architecture }}
#        shell: C:\cygwin\bin\bash.exe '{0}'
#      - name: Compile
#        run: make library
#      - name: Test Installation
#        run: sudo make install
#      - name: Run Tests
#        run: make test
