name: CI

on: [ push ]

jobs:
  testing:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
          - macos-latest
        compiler:
          - binary: clang
            configure-flags: ""
          - binary: gcc
            configure-flags: ""
          - binary: tcc
            configure-flags: -t
          - binary: sdcc
            configure-flags: -m
          - binary: pcc
            configure-flags: -t
        unhosted-flag:
          - ""
          - "-u"
        exclude:
          # SDCC has a bug in it on macOS that causes compilation to fail.
          - operating-system: macos-latest
            compiler:
              binary: sdcc
          # TODO (dargueta): Figure out what to do about incompatible headers
          - operating-system: macos-latest
            compiler:
              binary: tcc
          - operating-system: macos-latest
            compiler:
              binary: pcc
    steps:
      - uses: actions/checkout@v3

      - name: Install Compilers
        uses: ConorMacBride/install-package@v1
        with:
          apt: mingw-w64 pcc sdcc tcc
          brew: gcc sdcc

      # TCC can't be installed via Homebrew on recent versions of macOS because
      # of an "upstream incompatibility".
      - name: Install TCC on MacOS
        if: matrix.operating-system == 'macos-latest' && matrix.compiler.binary == 'tcc'
        run: make -C make -f compilers.mk install-tcc

      - name: Install PCC on MacOS
        if: matrix.operating-system == 'macos-latest' && matrix.compiler.binary == 'pcc'
        run: make -C make -f compilers.mk install-pcc

      - name: Fix header path on MacOS
        if: matrix.operating-system == 'macos-latest' && (matrix.compiler.binary == 'pcc' || matrix.compiler.binary == 'tcc')
        run: $(gcc -print-prog-name=cpp) -v < /dev/null

      - name: Configure
        run: |
          ./configure -d \
                      --cc=${{ matrix.compiler.binary }} \
                      ${{ matrix.unhosted-flag }} \
                      ${{ matrix.compiler.configure-flags }}

      - name: Compile
       # env:
       #   # Only needed on OSX for TCC/PCC. This is very hacky and will break if
       #   # they upgrade XCode on the Mac runners.
       #   CFLAGS: >-
       #     -I/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
       #     -I/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
       #     -I/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include
        run: make library

      - name: Test Installation
        run: sudo make install

      - name: Run Tests
        # We can't run cross-platform tests on SDCC
        if: matrix.compiler.binary != 'sdcc'
        run: make test

  testing-windows:
    runs-on: windows-latest
    env:
      SHELLOPTS: igncr
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe -o igncr '{0}'
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - binary: clang
            # Warnings need to be non-fatal when compiling tests due to an unused
            # static function in munit.
            configure-flags: -t
          - binary: gcc
            configure-flags: ""
          - binary: tcc
            configure-flags: -t
          # - binary: sdcc
          #   configure-flags: -m
        unhosted-flag:
          - ""
          - "-u"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: clang gcc perl texinfo

      - name: Install TCC if needed
        if: matrix.compiler.binary == 'tcc'
        run: make -C make -f compilers.mk install-tcc PREFIX=/usr

      - name: Install SDCC if needed
        if: matrix.compiler.binary == 'sdcc'
        run: make -C make -f compilers.mk install-sdcc PREFIX=/usr

      - name: Configure
        run: |
          ./configure -d \
                      --cc=${{ matrix.compiler.binary }} \
                      ${{ matrix.unhosted-flag }} \
                      ${{ matrix.compiler.configure-flags }}

      - name: Compile
        run: make library

      - name: Test Installation
        # Cygwin doesn't have sudo
        run: make install

      - name: Run Tests
        # We can't run cross-platform tests on SDCC
        if: matrix.compiler.binary != 'sdcc'
        run: make test
